### ISSUE TITLE
error with train_on_batch

### ISSUE THREAD

**Issue by kohheekyung** [Siddhartha24795/Medical-Image-Synthesis#1]
I'm interested in your great job.
I used datasets  'T1-T2'  in your github and run the code.

Do you have any idea about this error??

ipython-input-125-a3353993013f> in run_training_batch()
19 D_A_loss_real = model['D_A'].train_on_batch(x=real_images_A, y=ones)
20 D_B_loss_real = model['D_B'].train_on_batch(x=real_images_B, y=ones)
---> 21 D_A_loss_synthetic = model['D_A'].train_on_batch(x=synthetic_images_A, y=zeros)
22 D_B_loss_synthetic = model['D_B'].train_on_batch(x=synthetic_images_B, y=zeros)
23 D_A_loss = D_A_loss_real + D_A_loss_synthetic

ValueError: Error when checking input: expected input_85 to have shape (217, 181, 1) but got array with shape (220, 184, 1)

**Comment by Siddhartha24795** [comment]
check for the sizes of the image, maybe not all of same size
